# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('raw_idea', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(verbose_name='project description'),
        ),
    ]
