# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190118_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideas',
            old_name='date',
            new_name='pub_date',
        ),
    ]
